[project]
name = "bapsicle"
version = "3.1.1"
description = ""
authors = [
  { name = "University Radio York", email = "computing@ury.org.uk" }
]
readme = "README.md"

[project.scripts]
bapsicle = "launch:main"

[tool.poetry]
packages = [
  { include = "./*" }
]

[tool.poetry.dependencies]
python = ">=3.8.1,<3.14"
wheel = "^0.46.1"
pygame = "^2.5.2"
sanic = "^25.3.0"
sanic-cors = "^2.2.0"
syncer = "^2.0.3"
aiohttp = "^3.9.3"
mutagen = "^1.47.0"
sounddevice = "^0.5.2"
setproctitle = "^1.3.3"
pyttsx3 = "^2.90"
websockets = "^15.0"
typing-extensions = "^4.10.0"
pyserial = "^3.5"
requests = "^2.31.0"
jinja2 = "^3.1.3"
pydub = "^0.25.1"
psutil = "^7.0.0"

[tool.poetry.group.dev.dependencies]
pyinstaller = [
  {version = "^6.5.0", platform = "linux"},
  {version = "^6.5.0", platform = "darwin"}
]
auto-py-to-exe = {version = "^2.43.3", platform = "win32"}
pywin32 = {version = "^306", platform = "win32"}
autopep8 = "^2.1.0"
flake8 = "^7.0.0"
black = "^24.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
